name: mysterium_vpn_design
description: "Design system used in the MysteriumVPN app"
version: 0.0.4

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.35.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.2
  google_fonts: ^6.3.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: UntitledUI
      fonts:
        - asset: assets/fonts/UntitledUI.ttf
