name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mysterium_vpn_design:
    path: ../
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0


dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  widgetbook_generator: ^3.20.1

dependency_overrides:
  accessibility_tools: 2.8.0

flutter:
  uses-material-design: true
